"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
export const dynamic = "force-dynamic";
type Rede={nome:string;url:string};
type Integrante={nome:string;funcao:string};
type Disco={titulo:string;tipo:string;ano:string;link:string};
type Clipe={titulo:string;data:string;link:string};
export default function SiteConfig() {
  const router = useRouter();
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState<string|null>(null); const [saved,setSaved]=useState<string|null>(null);
  const [bio,setBio]=useState(""); const [logoUrl,setLogoUrl]=useState(""); const [redes,setRedes]=useState<Rede[]>([]); const [integrantes,setIntegrantes]=useState<Integrante[]>([]); const [discografia,setDiscografia]=useState<Disco[]>([]); const [clipes,setClipes]=useState<Clipe[]>([]);
  useEffect(()=>{ async function load(){ const {data:{session}}=await supabase.auth.getSession(); if (!session){router.push("/login");return;} const {data}=await supabase.from("site_config").select("key,value"); const cfg:Record<string,unknown>={}; (data||[]).forEach(row=>{cfg[row.key]=row.value;}); setBio((cfg.bio as string)||""); setLogoUrl((cfg.logo_url as string)||""); setRedes((cfg.redes as Rede[])||[]); setIntegrantes((cfg.integrantes as Integrante[])||[]); setDiscografia((cfg.discografia as Disco[])||[]); setClipes((cfg.clipes as Clipe[])||[]); setLoading(false); } load(); },[router]);
  async function save(key:string,value:unknown){ setSaving(key); const {data:{session}}=await supabase.auth.getSession(); await supabase.from("site_config").upsert({key,value,updated_by:session?.user.id,updated_at:new Date().toISOString()},{onConflict:"key"}); setSaving(null); setSaved(key); setTimeout(()=>setSaved(null),2000); }
  if (loading) return <div className="flex items-center justify-center py-20"><div className="w-6 h-6 rounded-full border-2 border-accent border-t-transparent animate-spin" /></div>;
  const Btn=({k,label,fn}:{k:string;label:string;fn:()=>void})=>(<button onClick={fn} disabled={saving===k} className="rounded-xl bg-accent/20 border border-accent/30 text-accent px-4 py-2 text-sm hover:bg-accent/30 disabled:opacity-50">{saving===k?"Salvando...":saved===k?"✓ Salvo!":label}</button>);
  const DISCO_TIPOS = ["Álbum","EP","Single","Coletânea","Outro"];
  return (<div className="space-y-10 max-w-2xl"><div><h1 className="font-display text-2xl text-bone">Site Público</h1><p className="text-bone/40 text-sm mt-1">Alterações aparecem imediatamente no site da banda.</p></div>
    <section className="space-y-3">
      <h2 className="text-xs uppercase tracking-widest text-bone/40">Logo da banda</h2>
      <input value={logoUrl} onChange={e=>setLogoUrl(e.target.value)} placeholder="https://... (URL da imagem da logo)" className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3 text-bone text-sm focus:outline-none focus:border-accent/50" />
      {logoUrl && <div className="flex items-center gap-3 p-3 rounded-xl bg-white/3 border border-white/8"><img src={logoUrl} alt="logo preview" className="h-12 w-auto object-contain rounded" onError={e=>{(e.target as HTMLImageElement).style.display="none"}} /><p className="text-xs text-bone/40">Preview da logo</p></div>}
      <Btn k="logo_url" label="Salvar logo" fn={()=>save("logo_url",logoUrl)} />
    </section>
    <section className="space-y-3"><h2 className="text-xs uppercase tracking-widest text-bone/40">Bio da banda</h2><textarea value={bio} onChange={e=>setBio(e.target.value)} rows={4} className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3 text-bone text-sm focus:outline-none focus:border-accent/50 resize-none" /><Btn k="bio" label="Salvar bio" fn={()=>save("bio",bio)} /></section>
    <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xs uppercase tracking-widest text-bone/40">Redes sociais</h2><button onClick={()=>setRedes(r=>[...r,{nome:"",url:""}])} className="text-xs text-accent">+ Adicionar</button></div>{redes.map((r,i)=>(<div key={i} className="flex gap-2"><input value={r.nome} onChange={e=>setRedes(rs=>rs.map((x,j)=>j===i?{...x,nome:e.target.value}:x))} placeholder="Nome" className="w-28 rounded-xl bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none" /><input value={r.url} onChange={e=>setRedes(rs=>rs.map((x,j)=>j===i?{...x,url:e.target.value}:x))} placeholder="https://..." className="flex-1 rounded-xl bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none" /><button onClick={()=>setRedes(rs=>rs.filter((_,j)=>j!==i))} className="text-bone/30 hover:text-accent px-2">&#215;</button></div>))}<Btn k="redes" label="Salvar redes" fn={()=>save("redes",redes)} /></section>
    <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xs uppercase tracking-widest text-bone/40">Integrantes</h2><button onClick={()=>setIntegrantes(r=>[...r,{nome:"",funcao:""}])} className="text-xs text-accent">+ Adicionar</button></div>{integrantes.map((m,i)=>(<div key={i} className="flex gap-2"><input value={m.nome} onChange={e=>setIntegrantes(ms=>ms.map((x,j)=>j===i?{...x,nome:e.target.value}:x))} placeholder="Nome" className="flex-1 rounded-xl bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none" /><input value={m.funcao} onChange={e=>setIntegrantes(ms=>ms.map((x,j)=>j===i?{...x,funcao:e.target.value}:x))} placeholder="Função" className="flex-1 rounded-xl bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none" /><button onClick={()=>setIntegrantes(ms=>ms.filter((_,j)=>j!==i))} className="text-bone/30 hover:text-accent px-2">&#215;</button></div>))}<Btn k="integrantes" label="Salvar integrantes" fn={()=>save("integrantes",integrantes)} /></section>
    <section className="space-y-3">
      <div className="flex items-center justify-between"><h2 className="text-xs uppercase tracking-widest text-bone/40">Discografia</h2><button onClick={()=>setDiscografia(d=>[...d,{titulo:"",tipo:"Álbum",ano:"",link:""}])} className="text-xs text-accent">+ Adicionar</button></div>
      {discografia.map((d,i)=>(<div key={i} className="rounded-xl border border-white/5 p-3 space-y-2">
        <div className="flex gap-2">
          <select value={d.tipo} onChange={e=>setDiscografia(ds=>ds.map((x,j)=>j===i?{...x,tipo:e.target.value}:x))} className="w-28 rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none">{DISCO_TIPOS.map(t=><option key={t}>{t}</option>)}</select>
          <input value={d.titulo} onChange={e=>setDiscografia(ds=>ds.map((x,j)=>j===i?{...x,titulo:e.target.value}:x))} placeholder="Título" className="flex-1 rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none" />
          <input value={d.ano} onChange={e=>setDiscografia(ds=>ds.map((x,j)=>j===i?{...x,ano:e.target.value}:x))} placeholder="Ano" className="w-16 rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none" />
          <button onClick={()=>setDiscografia(ds=>ds.filter((_,j)=>j!==i))} className="text-bone/30 hover:text-accent px-2">&#215;</button>
        </div>
        <input value={d.link} onChange={e=>setDiscografia(ds=>ds.map((x,j)=>j===i?{...x,link:e.target.value}:x))} placeholder="Link (Spotify, YouTube...)" className="w-full rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none" />
      </div>))}
      <Btn k="discografia" label="Salvar discografia" fn={()=>save("discografia",discografia)} />
    </section>
    <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xs uppercase tracking-widest text-bone/40">Clipes / Vídeos</h2><button onClick={()=>setClipes(c=>[...c,{titulo:"",data:"",link:""}])} className="text-xs text-accent">+ Adicionar</button></div>{clipes.map((c,i)=>(<div key={i} className="rounded-xl border border-white/5 p-3 space-y-2"><div className="flex gap-2"><input value={c.titulo} onChange={e=>setClipes(cs=>cs.map((x,j)=>j===i?{...x,titulo:e.target.value}:x))} placeholder="Título" className="flex-1 rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none" /><input value={c.data} onChange={e=>setClipes(cs=>cs.map((x,j)=>j===i?{...x,data:e.target.value}:x))} placeholder="Ano" className="w-20 rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none" /><button onClick={()=>setClipes(cs=>cs.filter((_,j)=>j!==i))} className="text-bone/30 hover:text-accent px-2">&#215;</button></div><input value={c.link} onChange={e=>setClipes(cs=>cs.map((x,j)=>j===i?{...x,link:e.target.value}:x))} placeholder="URL do YouTube" className="w-full rounded-lg bg-white/5 border border-white/10 px-3 py-2 text-bone text-sm focus:outline-none" /></div>))}<Btn k="clipes" label="Salvar clipes" fn={()=>save("clipes",clipes)} /></section>
  </div>);
}
